### PR TITLE
Added Dockerfile, start script, and documentation to README.

### PR DESCRIPTION
**Pull request by sabrsorensen**
I've bundled cloudplow on the official rclone Docker image and been able to successfully transfer using the daemon mode. I'm not sure if you're interested in a Docker image, but I thought I'd offer in case you were. Again, my apologies for not following the contributor guidelines earlier.

### CODE REVIEW

**Comment by desimaniac** [comment]
Cool! Will check it out soon.

**Comment by desimaniac** [comment]
Also do you mind if we also build an image of this under https://hub.docker.com/u/cloudb0x ?

**Comment by sabrsorensen** [comment]
I don't mind at all, go for it! I'd stop building mine and switch to the cloudbox image if you did.

**Comment by desimaniac** [comment]
Hey. Would it not be better if you had a separate rep for just the docker files (eg "docker-cloudplow"), instead of a fork of CP itself that youd have to keep maintaining?

**Comment by sabrsorensen** [comment]
I did that for a while, I don't remember why I switched to a fork anymore but a separate repo was much easier, I'll do that going forward.

**Comment by desimaniac** [comment]
No worries. I figured that that you need to have your own repo with full access vs me merging the dockerfile in but you needing PRs etc to maintain. We could then add installation info of your image into the readme here.

**Comment by sabrsorensen** [comment]
If you're still interested in taking a look, I brought https://hub.docker.com/repository/docker/sabrsorensen/alpine-cloudplow up to date with the same changes I'd been tracking in this PR, with a simple docker-compose example and the corresponding Docker-specific config.json entries in the README and Docker Hub description.

**Comment by rafaelreis-r** [comment]
Hey guys. 

Long time CloudPlow user here. Decided to try the Docker image on a windows host to simplify backup automation on windows systems. It takes some tinkering but it seems to work, despite one issue mentioned afterwards. 

Here is run command:

```
docker run -d --name=cloudplow -e PUID=1001 -e PGID=1001 -e TZ=<set-yours> -e PYTHONIOENCODING=UTF-8 -e CLOUDPLOW_CONFIG=/config/config.json -e CLOUDPLOW_LOGFILE=/config/cloudplow.log -e CLOUDPLOW_LOGLEVEL=DEBUG -e CLOUDPLOW_CACHEFILE=/config/cache.db --restart unless-stopped -v  <config_dir>:/config:rw -v <rclone_conf_dir>:/rclone_config:rw -v <folder_or_volume_name>:/data/imported_media:rw sabrsorensen/alpine-cloudplow
```

Since my data was on a NAS, and Docker doesn't let you share network drives to containers, I had to create a docker volume with the CIFS mount to the NAS as the data source:

`docker volume create --driver local --opt type=cifs --opt device=//<NAS_IP/folder> --opt o=user=<user>,domain=WORKGROUP,password=<pass>,iocharset=utf8 <volume_name>`

Important to use the iocharset setting, otherwise it will not deal with utf8 chars.

Reused a config.json from another machine with minor adjustments. It seems to be fine. One issue though:

It does not what is scheduled to do. As if the service wasn't enabled. I'll try some other configurations settings here to isolate if this is a windows docker thing or just a bad config.

This is the docker run output:

```
User 'cloudplow' created.
------------------------------------
New user ID info: uid=1001(cloudplow) gid=1001(cloudplow) groups=1001(cloudplow)

Permissions on /config and /opt/cloudplow restored successfully.
[cont-init.d] 10-init_user_and_fix_permissions: exited 0.
[cont-init.d] 20-cleanup_stale_locks: executing...
[cont-init.d] 20-cleanup_stale_locks: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

2020-05-11 15:46:15,953 - DEBUG - config - load - Upgrading config...
2020-05-11 15:46:15,955 - DEBUG - config - load - Config was not upgraded as there were no changes to add.
2020-05-11 15:46:16,013 - INFO - lock - ensure_lock_folder - Created lock folder: '/opt/cloudplow/locks'
2020-05-11 15:46:16,015 - DEBUG - git.cmd - execute - Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/cloudplow, universal_newlines=False, shell=None, istream=<valid stream>)
2020-05-11 15:46:16,024 - DEBUG - git.cmd - execute - Popen(['git', 'fetch', '-v', 'origin'], cwd=/opt/cloudplow, universal_newlines=True, shell=None, istream=None)
2020-05-11 15:46:16,529 - DEBUG - git - check_version - You are using the latest master: 9cab62a3c079fed182bcc0d57d34ddee05a939ce
2020-05-11 15:46:16,531 - INFO - cloudplow - <module> - Started in run mode
2020-05-11 15:46:16,532 - INFO - pushover - __init__ - Initialized Pushover notification agent
2020-05-11 15:46:16,534 - DEBUG - cloudplow - init_service_accounts - Start initializing of service accounts.
2020-05-11 15:46:16,535 - DEBUG - cloudplow - init_service_accounts - Finished initializing of service accounts.
2020-05-11 15:46:16,537 - INFO - local - __init__ - Initialized Local syncer agent for 'bckp2crypt' - /data/imported_media -> crypt:Backups using tool: '/usr/bin/rclone'
2020-05-11 15:46:16,539 - INFO - cloudplow - <module> - Added bckp2crypt syncer to schedule, syncing every 0 hours

[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-init_user_and_fix_permissions: executing...

PUID: 1001

UID: 1001

PGID: 1001

GID: 1001

Group 'cloudplow' for running cloudplow exists: cloudplow:x:1001
User 'cloudplow' for running cloudplow exists: cloudplow:x:1001:1001::/home/cloudplow:/sbin/nologin

2020-05-11 15:50:21,421 - DEBUG - config - load - Upgrading config...
2020-05-11 15:50:21,424 - DEBUG - config - load - Config was not upgraded as there were no changes to add.
2020-05-11 15:50:21,443 - INFO - lock - ensure_lock_folder - Created lock folder: '/opt/cloudplow/locks'
2020-05-11 15:50:21,445 - DEBUG - git.cmd - execute - Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/cloudplow, universal_newlines=False, shell=None, istream=<valid stream>)
2020-05-11 15:50:21,456 - DEBUG - git.cmd - execute - Popen(['git', 'fetch', '-v', 'origin'], cwd=/opt/cloudplow, universal_newlines=True, shell=None, istream=None)
2020-05-11 15:50:21,948 - DEBUG - git - check_version - You are using the latest master: 9cab62a3c079fed182bcc0d57d34ddee05a939ce
2020-05-11 15:50:21,950 - INFO - cloudplow - <module> - Started in run mode
2020-05-11 15:50:21,952 - INFO - pushover - __init__ - Initialized Pushover notification agent
2020-05-11 15:50:21,954 - DEBUG - cloudplow - init_service_accounts - Start initializing of service accounts.
2020-05-11 15:50:21,957 - DEBUG - cloudplow - init_service_accounts - Finished initializing of service accounts.
2020-05-11 15:50:21,959 - INFO - local - __init__ - Initialized Local syncer agent for 'bckp2crypt' - /data/imported_media -> crypt:Backups using tool: '/usr/bin/rclone'
2020-05-11 15:50:21,961 - INFO - cloudplow - <module> - Added bckp2crypt syncer to schedule, syncing every 24 hours
2020-05-11 16:18:57,205 - DEBUG - config - load - Upgrading config...
2020-05-11 16:18:57,208 - DEBUG - config - load - Config was not upgraded as there were no changes to add.
2020-05-11 16:18:57,227 - INFO - lock - ensure_lock_folder - Created lock folder: '/opt/cloudplow/locks'
2020-05-11 16:18:57,229 - DEBUG - git.cmd - execute - Popen(['git', 'cat-file', '--batch-check'], cwd=/opt/cloudplow, universal_newlines=False, shell=None, istream=<valid stream>)
2020-05-11 16:18:57,241 - DEBUG - git.cmd - execute - Popen(['git', 'fetch', '-v', 'origin'], cwd=/opt/cloudplow, universal_newlines=True, shell=None, istream=None)
2020-05-11 16:18:57,814 - DEBUG - git - check_version - You are using the latest master: 9cab62a3c079fed182bcc0d57d34ddee05a939ce
2020-05-11 16:18:57,816 - INFO - cloudplow - <module> - Started in run mode
2020-05-11 16:18:57,818 - INFO - pushover - __init__ - Initialized Pushover notification agent
2020-05-11 16:18:57,820 - DEBUG - cloudplow - init_service_accounts - Start initializing of service accounts.
2020-05-11 16:18:57,824 - DEBUG - cloudplow - init_service_accounts - Finished initializing of service accounts.
2020-05-11 16:18:57,825 - INFO - local - __init__ - Initialized Local syncer agent for 'bckp2crypt' - /data/imported_media -> crypt:Backups using tool: '/usr/bin/rclone'
2020-05-11 16:18:57,826 - INFO - cloudplow - <module> - Added bckp2crypt syncer to schedule, syncing every 1 hours
```

```json
{
    "core": {
        "dry_run": false,
        "rclone_binary_path": "/usr/bin/rclone",
        "rclone_config_path": "/rclone_config/rclone.conf"
    },
    "hidden": {},
    "notifications": {
        "Pushover": {
            "app_token": "REDACTED",
            "priority": 0,
            "service": "pushover",
            "user_token": "REDACTED"
        }
    },
    "nzbget": {
        "enabled": false,
        "url": "https://user:password@nzbget.domain.com"
    },
    "plex": {
        "enabled": false,
        "max_streams_before_throttle": 1,
        "notifications": false,
        "poll_interval": 60,
        "rclone": {
            "throttle_speeds": {
                "1": "50M",
                "2": "40M",
                "3": "30M",
                "4": "20M",
                "5": "10M"
            },
            "url": "http://localhost:7949"
        },
        "token": "",
        "url": "https://plex.domain.com"
    },
    "remotes": {
        "google": {
            "hidden_remote": "",
            "rclone_excludes": [],
            "rclone_extras": {},
            "rclone_sleeps": {},
            "remove_empty_dir_depth": 2,
            "sync_remote": "crypt:Backups",
            "upload_folder": "",
            "upload_remote": ""
        },
        "localb": {
            "hidden_remote": "",
            "rclone_excludes": [],
            "rclone_extras": {},
            "rclone_sleeps": {
                " 0/s,": {
                    "count": 15,
                    "sleep": 25,
                    "timeout": 140
                },
                "Failed to copy: googleapi: Error 403: User rate limit exceeded": {
                    "count": 5,
                    "sleep": 25,
                    "timeout": 3600
                }
            },
            "remove_empty_dir_depth": 2,
            "sync_remote": "/data/imported_media",
            "upload_folder": "",
            "upload_remote": ""
        }
    },
    "syncer": {
        "bckp2crypt": {
             "schedule": {
                "allowed_from": "02:00",
                "allowed_until": "05:00",
                "enabled": true
            },
            "instance_destroy": false,
            "rclone_extras": {
                "--bwlimit": "5M",
                "--checkers": 2,
                "--drive-chunk-size": "64M",
                "--fast-list": null,
                "--stats": "60s",
                "--tpslimit": 10,
                "--tpslimit-burst": 25,
                "--transfers": 1,
                "--verbose": 1
            },
            "service": "local",
            "sync_from": "localb",
            "sync_interval": 1,
            "sync_to": "google",
            "tool_path": "/usr/bin/rclone",
            "use_copy": false
        }
    },
    "uploader": {}
}
```

If I set the sync_interval to 0, it ignores the scheduler and starts the sync right away nonstop. Any number above 0 results in no operations.

I have no knowledge debugging services inside linux containers. There are no known systemctl, service etc commands to use. If you could point me out in a direction I could maybe debug what could be going on.

Thanks for the great work.

**Comment by sabrsorensen** [comment]
It's normal operation for cloudplow to wait for the sync interval to expire before starting a transfer job, so that makes sense what you've seen with 0 vs not 0. If you set it to 1 and leave the Docker run command running for 1 minute, does a transfer job start? Or do you see no transfer jobs running even after allowing `sync_interval` minutes to pass?

**Comment by rafaelreis-r** [comment]
I left it for over 24hs. There was no action on the containers part. sync_interval is in hours. 

This is very odd because it does work on with the same settings on other linux systems. 
Notice that I have scheduler enabled. I should be getting an output similar to this, when the sync is not within the scheduled hours, it outputs a message saying that It will not run since it is not within the scheduler timeframe. I'm not getting that message either. 

I'm able to bash into the container, I can verify that the data dir is mounted and readable, and I can even run a manual cloudplow sync. It works.

The service / auto part for some reason doesn't seem to be running.

**Comment by sabrsorensen** [comment]
`ps -ef` should show the running processes in the container, do you see a Python or s6-exec process running /opt/cloudplow/cloudplow.py?

**Comment by rafaelreis-r** [comment]
> `ps -ef` should show the running processes in the container, do you see a Python or s6-exec process running /opt/cloudplow/cloudplow.py?

```
/opt/cloudplow # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   34 root      0:00 s6-supervise s6-fdholderd
  220 root      0:00 s6-supervise cloudplow
  223 cloudplo  0:01 python3 /opt/cloudplow/cloudplow.py run
  258 cloudplo  0:00 git cat-file --batch-check
  266 root      0:00 /bin/sh
  275 root      0:00 /bin/sh
  282 root      0:00 ps -ef
/opt/cloudplow #    
```

**Comment by sabrsorensen** [comment]
I haven't used the syncer functionality, I'll try creating a similar config on my system and testing locally as well.

**Comment by rafaelreis-r** [comment]
It is alive. Syncer started after 1 hour but completely ignored the scheduler limits. Not sure now if this is a cloudplow implementation limitation or just a bad config. I suspect that the scheduler is implemented only for uploader tasks, although it is not clear on CP docs.

```
2020-05-12 10:19:51,216 - INFO       - cloudplow            - <module>                       - Added bckp2crypt syncer to schedule, syncing every 1 hours
2020-05-12 11:19:51,367 - INFO       - cloudplow            - scheduled_syncer               - Scheduled sync triggered for syncer: bckp2crypt
2020-05-12 11:19:51,380 - INFO       - cloudplow            - do_sync                        - Starting sync
2020-05-12 11:19:52,282 - INFO       - notifications        - send                           - Sent notification with Pushover
2020-05-12 11:19:52,284 - INFO       - local                - sync                           - Starting sync for instance: 9131
2020-05-12 11:19:52,288 - DEBUG      - rclone               - sync                           - Using: /usr/bin/rclone sync /data/imported_media crypt:Backups --bwlimit=5M --checkers=2 --drive-chunk-size=64M --fast-list --stats=60s --tpslimit=10 --tpslimit-burst=25 --transfers=1 --verbose=1 --config=/rclone_config/rclone.conf
2020-05-12 11:19:52,339 - INFO       - process              - execute                        - 2020/05/12 11:19:52 INFO  : Starting bandwidth limiter at 5MBytes/s
2020-05-12 11:19:52,341 - INFO       - process              - execute                        - 2020/05/12 11:19:52 INFO  : Starting HTTP transaction limiter: max 10 transactions/s with burst 25
2020-05-12 11:20:39,168 - INFO       - process              - execute                        - 2020/05/12 11:20:39 INFO  : Encrypted drive 'crypt:Backups': Waiting for checks to finish
2020-05-12 11:20:39,169 - INFO       - process              - execute                        - 2020/05/12 11:20:39 INFO  : Encrypted drive 'crypt:Backups': Waiting for transfers to finish
2020-05-12 11:21:12,895 - INFO       - process              - execute                        - 2020/05/12 11:21:12 INFO  :
2020-05-12 11:21:12,896 - INFO       - process              - execute                        - Transferred:       219.491M / 189.023 GBytes, 0%, 4.981 MBytes/s, ETA 10h46m55s
2020-05-12 11:21:12,898 - INFO       - process              - execute                        - Checks:              1741 / 1741, 100%
2020-05-12 11:21:12,899 - INFO       - process              - execute                        - Transferred:            0 / 36, 0%
2020-05-12 11:21:12,900 - INFO       - process              - execute                        - Elapsed time:        44.0s
```

Anyways, this is a success case of adapting the docker container to windows hosts, in case anybody else needs such a setup. 

Thanks again @sabrsorensen and @l3uddz @desimaniac for the awesome job.

**Pull request closed without merging**
